package org.example.meetlearning.dao.entity;

import lombok.Data;

import java.util.Date;


@Data
public class TeacherSchedule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_schedule.id
     *
     * @mbg.generated Sun Mar 16 15:57:16 CST 2025
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_schedule.creator
     *
     * @mbg.generated Sun Mar 16 15:57:16 CST 2025
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_schedule.create_time
     *
     * @mbg.generated Sun Mar 16 15:57:16 CST 2025
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_schedule.teacher_id
     *
     * @mbg.generated Sun Mar 16 15:57:16 CST 2025
     */
    private String teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_schedule.begin_time
     *
     * @mbg.generated Sun Mar 16 15:57:16 CST 2025
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_schedule.end_time
     *
     * @mbg.generated Sun Mar 16 15:57:16 CST 2025
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_schedule.week_num
     *
     * @mbg.generated Sun Mar 16 15:57:16 CST 2025
     */
    private String weekNum;

}