package org.example.meetlearning.dao.entity;

import lombok.Data;

import java.util.Date;

@Data
public class TeacherScheduleSet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_schedule_set.id
     *
     * @mbg.generated Sun Mar 16 15:57:16 CST 2025
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_schedule_set.creator
     *
     * @mbg.generated Sun Mar 16 15:57:16 CST 2025
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_schedule_set.create_time
     *
     * @mbg.generated Sun Mar 16 15:57:16 CST 2025
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_schedule_set.teacher_id
     *
     * @mbg.generated Sun Mar 16 15:57:16 CST 2025
     */
    private String teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_schedule_set.begin_time
     *
     * @mbg.generated Sun Mar 16 15:57:16 CST 2025
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_schedule_set.end_time
     *
     * @mbg.generated Sun Mar 16 15:57:16 CST 2025
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_schedule_set.week_num
     *
     * @mbg.generated Sun Mar 16 15:57:16 CST 2025
     */
    private String weekNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_schedule_set.schedule_type
     *
     * @mbg.generated Sun Mar 16 15:57:16 CST 2025
     */
    private String scheduleType;
}