package org.example.meetlearning.dao.entity;

import lombok.Data;

import java.util.Date;

@Data
public class Textbook {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook.id
     *
     * @mbg.generated Tue Apr 08 22:33:54 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook.deleted
     *
     * @mbg.generated Tue Apr 08 22:33:54 CST 2025
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook.creator
     *
     * @mbg.generated Tue Apr 08 22:33:54 CST 2025
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook.create_name
     *
     * @mbg.generated Tue Apr 08 22:33:54 CST 2025
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook.create_time
     *
     * @mbg.generated Tue Apr 08 22:33:54 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook.updator
     *
     * @mbg.generated Tue Apr 08 22:33:54 CST 2025
     */
    private String updator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook.update_name
     *
     * @mbg.generated Tue Apr 08 22:33:54 CST 2025
     */
    private String updateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook.update_time
     *
     * @mbg.generated Tue Apr 08 22:33:54 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook.record_id
     *
     * @mbg.generated Tue Apr 08 22:33:54 CST 2025
     */
    private String recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook.name
     *
     * @mbg.generated Tue Apr 08 22:33:54 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook.level_begin
     *
     * @mbg.generated Tue Apr 08 22:33:54 CST 2025
     */
    private Integer levelBegin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook.level_end
     *
     * @mbg.generated Tue Apr 08 22:33:54 CST 2025
     */
    private Integer levelEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook.type
     *
     * @mbg.generated Tue Apr 08 22:33:54 CST 2025
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column textbook.catalog
     *
     * @mbg.generated Tue Apr 08 22:33:54 CST 2025
     */
    private String catalog;
}